### ISSUE TITLE
Morning and Zenburn themes broken on mobile

### ISSUE THREAD

**Issue by floogulinc** [Shuo-IRC/Shuo#46]
The connect and settings buttons are invisible.

Morning | Zenburn
---- | ----
![screenshot_2015-08-09-06-27-33](https://cloud.githubusercontent.com/assets/1300395/9154639/4f8b502c-3e60-11e5-84c2-83ac8ffb0c7c.png) | ![screenshot_2015-08-09-06-27-53](https://cloud.githubusercontent.com/assets/1300395/9154640/52cf1516-3e60-11e5-996c-2bcaa200f80e.png)
![ios simulator screen shot 9 aug 2015 06 35 25](https://cloud.githubusercontent.com/assets/1300395/9154650/d3707a70-3e60-11e5-8b6f-c5e686444e37.png) | ![ios simulator screen shot 9 aug 2015 06 22 35](https://cloud.githubusercontent.com/assets/1300395/9154641/55fbca72-3e60-11e5-8b64-640e5c7e71db.png)

**Comment by YaManicKill** [comment]
Yep, also an issue for me. What I wonder is...is there a way I can get to the settings with it being invisible now?
